path_base_CD: ${PATH_data}/clip_datasets
n_tuning_task: 0
n_task: 60
image_size: 224

datasets:
  - oxford_pets
  - eurosat
  - ucf101
  - sun397
  - caltech101
  - dtd
  - fgvc
  - food101
  - oxford_flowers
  - stanford_cars
#  - imagenet